### ISSUE TITLE
use Domain in addr error

### ISSUE THREAD

**Issue by MikoyChinese** [zephyrchien/midori#2]
Hi,

I wanna try midori in my host(Debian 10), and I create a config file as following:

```
{
  "dns_mode": "ipv4_only",
  "endpoints": [
      {
        "listen": {
          "addr": "0.0.0.0:30760"
        },
        "remote": {
          "addr": "us-test.example.com:12345",
          "trans": {
            "proto": "ws",
            "path": "/0c921660a10729a81048961df5b3a125"
          }
        }
      }
  ]
}

```

But when I run `/midori -c config.json`, I got a error:

```bash
PanicInfo { payload: Any { .. }, message: None, location: Location { file: "/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/enter.rs", line: 39, col: 9 } }
```

If I change the remote's addr to IP such as x.x.x.x, I can run the command successfully.

**Comment by zephyrchien** [comment]
That was caused by the sync dns resolver, which attended to build another runtime when checking the remote address. Now I have fixed it, thanks a lot for your report!
