### ISSUE TITLE
Port range support

### ISSUE THREAD

**Issue by theBucky** [zephyrchien/midori#5]
Hi,

Love your work!

was testing your zero-copy supported forked of the realm, but it seems to have performance issues. Fortunately, midori has no issues with performance so far.

any plans on supporting port range forwarding?

**Comment by zephyrchien** [comment]
Thanks :)

The zero-copy implementation of midori and realm is the same. **Did you enable zero-copy with `-z` or `zero_copy=true` ?**

> any plans on supporting port range forwarding?

Not yet. The feature is rarely necessary, and easily abused. I recommend users to write multiple configurations, or write a script to generate the config file.
