### ISSUE TITLE
Questions about dns in midori

### ISSUE THREAD

**Issue by aa51513** [zephyrchien/midori#7]
Hi,there

I've been using midori for a while now and I think it's a very useful tool and I really like it.

During use, I encountered a small problem, to be precise, a small question: after configuring the domain name in endpoints.remote.addr, **will the DNS resolution result be cached, and how long is the default cache time?**
I ask this question because I want to access a service whose IP changes frequently but the domain name remains the same through a fixed address (my local IP and port)

Below is my config file content

`{
  "dns_mode": "ipv4_then_ipv6",
  "endpoints": [
    {
      "listen": {
        "addr": "127.0.0.1:5000",
        "net": "tcp",
        "trans": {
          "proto": "ws",
          "path": "/ws"
        }
      },
      "remote": {
        "addr": "ip.myserver.com:443",
        "net": "tcp",
        "trans": {
          "proto": "ws",
          "path": "/ws"
        },
        "tls": {
          "roots": "firefox",
          "versions": "tlsv1.3",
          "sni": "api.myserver.com",
          "aplns": "http/1.1",
          "skip_verify": false,
          "enable_sni": true
        }
      }
    }
  ]
}`

In my scenario, the IP addresses corresponding to domain ‘api.myserver.com’ and domain ‘ip.myserver.com’ are always the same，and change frequently

**Comment by zephyrchien** [comment]
>  will the DNS resolution result be cached, and how long is the default cache time

Generally speaking, It will. The expiration time depends on the `TTL` value received from your dns server.

The program itself does not cache the result, it always performs dns lookup before connecting to your remote server. It is the underlying library(trust-dns) that caches the result.

BTW, the default upstream dns server is `8.8.8.8`, `8.8.4.4`, which is currently not configurable. I'm going to provide more options for dns configuration, such as custom upstream server and custom min&max TTL value.

**Comment by aa51513** [comment]
> > will the DNS resolution result be cached, and how long is the default cache time
> 
> Generally speaking, It will. The expiration time depends on the `TTL` value received from your dns server.
> 
> The program itself does not cache the result, it always performs dns lookup before connecting to your remote server. It is the underlying library(trust-dns) that caches the result.
> 
> BTW, the default upstream dns server is `8.8.8.8`, `8.8.4.4`, which is currently not configurable. I'm going to provide more options for dns configuration, such as custom upstream server and custom min&max TTL value.

Thank you very much for taking the time out of your busy schedule to reply to me.
I really look forward to your new features, 
Thank you again for making such a useful tool.
