### ISSUE TITLE
Will you consider releasing a docker image?

### ISSUE THREAD

**Issue by aa51513** [zephyrchien/midori#8]
Midori is a tool I love and it's so stable that I want to use it for my own services.

Considering that my existing service is built on the docker platform, I need a midori docker image.

But I couldn't find any official or unofficial midori images on docker.com, 

do you have any plans to release docker images in the future?

**Comment by zephyrchien** [comment]
You can refer to [shadowsocks-rust's dockerfile](https://raw.githubusercontent.com/shadowsocks/shadowsocks-rust/master/Dockerfile) to build a image on your own.

**Comment by zephyrchien** [comment]
[zephyrchien/midori](https://hub.docker.com/r/zephyrchien/midori) I've built one just now, it is for `x86_64`.

To build images for other platforms, you can fork this project and make use of github workflow.(also refer to [shadowsocks-rust](https://raw.githubusercontent.com/shadowsocks/shadowsocks-rust/master/.github/workflows/build-docker-image.yml))

**Comment by aa51513** [comment]
> [zephyrchien/midori](https://hub.docker.com/r/zephyrchien/midori) I've built one just now, it is for `x86_64`.
> 
> To build images for other platforms, you can fork this project and make use of github workflow.(also refer to [shadowsocks-rust](https://raw.githubusercontent.com/shadowsocks/shadowsocks-rust/master/.github/workflows/build-docker-image.yml))

Thank you very much
